image: cirrusci/flutter:stable

stages:
  - build
  - analyze
  - test

build:
  stage: build

  script:
    - flutter build aot

unit_test:
  stage: test

  script:
    - flutter test test/*
analyze:
  stage: analyze

  script:
    - echo job excluded